remote_theme: pmarsceill/just-the-docs
layout: default
---
title: Introduction
nav_order: 1
---
title: Images
nav_order: 2
---
title: Interval and Click Delay
nav_order: 3
---
title: Black and Transparency Thresholds
nav_order: 4
---
title: Settings and Info
nav_order: 5
---
title: Support
nav_order: 6
---
